data = {10000002: ['神里绫华', '神里绫华', '神里绫华', '神里绫华', '神里绫华', 'Kamisato Ayaka', 'Kamisato Ayaka', 'Kamisato Ayaka',
                   'Kamisato Ayaka', 'Kamisato Ayaka', 'Kamisato Ayaka', 'Kamisato Ayaka'],
        10000016: ['迪卢克', '迪卢克', '迪卢克', '迪卢克', '迪卢克', 'Diluc', 'Diluc', 'Diluc', 'Diluc', 'Diluc', 'Diluc', 'Diluc',
                   'Diluc'],
        10000022: ['温迪', '温迪', '温迪', '温迪', '温迪', '温迪', 'Venti', 'Venti', 'Venti', 'Venti', 'Venti', 'Venti'],
        10000029: ['可莉', '可莉', '可莉', 'Klee', 'Klee', 'Klee'],
        10000030: ['钟离', '钟离', '钟离', '钟离', '钟离', '钟离', '钟离', 'Zhongli', 'Zhongli', 'Zhongli', 'Zhongli', 'Zhongli',
                   'Zhongli', 'Zhongli', 'Zhongli', 'Zhongli'],
        10000033: ['达达利亚', '达达利亚', '达达利亚', 'Tartaglia', 'Tartaglia', 'Tartaglia', 'Tartaglia', 'Tartaglia'],
        10000035: ['七七', '七七', '七七', '七七', '七七', '七七', '七七', 'Qiqi', 'Qiqi', 'Qiqi', 'Qiqi', 'Qiqi', 'Qiqi', 'Qiqi',
                   'Qiqi'],
        10000037: ['甘雨', '甘雨', '甘雨', '甘雨', '甘雨', '甘雨', '甘雨', 'Ganyu', 'Ganyu', 'Ganyu', 'Ganyu', 'Ganyu', 'Ganyu'],
        10000041: ['莫娜', '莫娜', '莫娜', '莫娜', '莫娜', '莫娜', '莫娜', 'Mona', 'Mona', 'Mona', 'Mona', 'Mona', 'Mona'],
        10000046: ['胡桃', '胡桃', '胡桃', '胡桃', 'Hu Tao', 'Hu Tao', 'Hu Tao', 'Hu Tao', 'Hu Tao'],
        10000047: ['枫原万叶', '枫原万叶', '枫原万叶', '枫原万叶', '枫原万叶', '枫原万叶', 'Kaedehara Kazuha', 'Kaedehara Kazuha',
                   'Kaedehara Kazuha', 'Kaedehara Kazuha', 'Kaedehara Kazuha', 'Kaedehara Kazuha', 'Kaedehara Kazuha',
                   'Kaedehara Kazuha', 'Kaedehara Kazuha'],
        10000052: ['雷电将军', '雷电将军', '雷电将军', '雷电将军', '雷电将军', '雷电将军', '雷电将军', 'Raiden Shogun', 'Raiden Shogun',
                   'Raiden Shogun', 'Raiden Shogun', 'Raiden Shogun', 'Raiden Shogun', 'Raiden Shogun'],
        10000054: ['珊瑚宫心海', '珊瑚宫心海', '珊瑚宫心海', '珊瑚宫心海', '珊瑚宫心海', 'Sangonomiya Kokomi', 'Sangonomiya Kokomi',
                   'Sangonomiya Kokomi', 'Sangonomiya Kokomi', 'Sangonomiya Kokomi', 'Sangonomiya Kokomi',
                   'Sangonomiya Kokomi'], 10000058: ['八重神子', '八重神子', 'Yae Miko', 'Yae Miko', 'Yae Miko', 'Yae Miko'],
        10000060: ['夜兰', '夜兰', '夜兰', '夜兰', '夜兰', 'Yelan', 'Yelan', 'Yelan', 'Yelan', 'Yelan', 'Yelan', 'Yelan'],
        10000063: ['申鹤', '申鹤', 'Shenhe', 'Shenhe', 'Shenhe', 'Shenhe', 'Shenhe'],
        10000023: ['香菱', '香菱', '香菱', '香菱', '香菱', '香菱', '香菱', 'Xiangling', 'Xiangling', 'Xiangling', 'Xiangling',
                   'Xiangling', 'Xiangling', 'Xiangling', 'Xiangling', 'Xiangling'],
        10000025: ['行秋', '行秋', '行秋', '行秋', '行秋', '行秋', '行秋', 'Xingqiu', 'Xingqiu', 'Xingqiu', 'Xingqiu', 'Xingqiu',
                   'Xingqiu', 'Xingqiu', 'Xingqiu', 'Xingqiu'],
        10000031: ['菲谢尔', '菲谢尔', '菲谢尔', '菲谢尔', '菲谢尔', '菲谢尔', '菲谢尔', 'Fischl', 'Fischl', 'Fischl', 'Fischl', 'Fischl',
                   'Fischl', 'Fischl', 'Fischl', 'Fischl'],
        10000032: ['班尼特', '班尼特', '班尼特', '班尼特', '班尼特', '班尼特', '班尼特', 'Bennett', 'Bennett', 'Bennett', 'Bennett',
                   'Bennett', 'Bennett', 'Bennett', 'Bennett', 'Bennett'],
        10000045: ['罗莎莉亚', '罗莎莉亚', '罗莎莉亚', '罗莎莉亚', '罗莎莉亚', '罗莎莉亚', '罗莎莉亚', 'Rosaria', 'Rosaria', 'Rosaria', 'Rosaria',
                   'Rosaria', 'Rosaria', 'Rosaria', 'Rosaria', 'Rosaria'],
        10000056: ['九条裟罗', '九条裟罗', '九条裟罗', '九条裟罗', '九条裟罗', '九条裟罗', '九条裟罗', 'Kujou Sara', 'Kujou Sara', 'Kujou Sara',
                   'Kujou Sara', 'Kujou Sara', 'Kujou Sara', 'Kujou Sara', 'Kujou Sara'],
        10000057: ['荒泷一斗', '荒泷一斗', '荒泷一斗', 'Arataki Itto', 'Arataki Itto', 'Arataki Itto', 'Arataki Itto',
                   'Arataki Itto'],
        10000039: ['迪奥娜', '迪奥娜', '迪奥娜', '迪奥娜', '迪奥娜', '迪奥娜', '迪奥娜', 'Diona', 'Diona', 'Diona', 'Diona', 'Diona',
                   'Diona', 'Diona', 'Diona', 'Diona'],
        10000043: ['砂糖', '砂糖', '砂糖', '砂糖', '砂糖', '砂糖', '砂糖', 'Sucrose', 'Sucrose', 'Sucrose', 'Sucrose', 'Sucrose',
                   'Sucrose', 'Sucrose', 'Sucrose', 'Sucrose'],
        10000055: ['五郎', '五郎', '五郎', '五郎', '五郎', '五郎', 'Gorou', 'Gorou', 'Gorou', 'Gorou', 'Gorou', 'Gorou', 'Gorou'],
        10000020: ['雷泽', '雷泽', '雷泽', '雷泽', '雷泽', '雷泽', '雷泽', 'Razor', 'Razor', 'Razor', 'Razor', 'Razor', 'Razor',
                   'Razor', 'Razor', 'Razor'],
        10000049: ['宵宫', '宵宫', 'Yoimiya', 'Yoimiya', 'Yoimiya', 'Yoimiya', 'Yoimiya'],
        10000007: ['旅行者', '旅行者', '旅行者', '旅行者', '旅行者', 'Traveler', 'Traveler', 'Traveler'],
        10000014: ['芭芭拉', '芭芭拉', '芭芭拉', '芭芭拉', '芭芭拉', '芭芭拉', '芭芭拉', 'Barbara', 'Barbara', 'Barbara', 'Barbara',
                   'Barbara', 'Barbara', 'Barbara', 'Barbara', 'Barbara'],
        10000027: ['凝光', '凝光', '凝光', '凝光', '凝光', '凝光', '凝光', 'Ningguang', 'Ningguang', 'Ningguang', 'Ningguang',
                   'Ningguang', 'Ningguang', 'Ningguang', 'Ningguang', 'Ningguang'],
        10000042: ['刻晴', '刻晴', '刻晴', '刻晴', '刻晴', '刻晴', 'Keqing', 'Keqing', 'Keqing', 'Keqing', 'Keqing', 'Keqing',
                   'Keqing'],
        10000006: ['丽莎', '丽莎', '丽莎', '丽莎', '丽莎', '丽莎', '丽莎', 'Lisa', 'Lisa', 'Lisa', 'Lisa', 'Lisa', 'Lisa', 'Lisa',
                   'Lisa', 'Lisa'],
        10000021: ['安柏', '安柏', '安柏', '安柏', '安柏', '安柏', '安柏', 'Amber', 'Amber', 'Amber', 'Amber', 'Amber', 'Amber',
                   'Amber', 'Amber', 'Amber'],
        10000048: ['烟绯', '烟绯', '烟绯', '烟绯', '烟绯', '烟绯', '烟绯', 'Yanfei', 'Yanfei', 'Yanfei', 'Yanfei', 'Yanfei', 'Yanfei',
                   'Yanfei', 'Yanfei', 'Yanfei'],
        10000003: ['琴', '琴', '琴', '琴', '琴', 'Jean', 'Jean', 'Jean', 'Jean', 'Jean', 'Jean', 'Jean', 'Jean', 'Jean'],
        10000036: ['重云', '重云', '重云', '重云', '重云', '重云', '重云', 'Chongyun', 'Chongyun', 'Chongyun', 'Chongyun', 'Chongyun',
                   'Chongyun', 'Chongyun', 'Chongyun'],
        10000015: ['凯亚', '凯亚', '凯亚', '凯亚', '凯亚', '凯亚', '凯亚', 'Kaeya', 'Kaeya', 'Kaeya', 'Kaeya', 'Kaeya', 'Kaeya',
                   'Kaeya', 'Kaeya', 'Kaeya'],
        10000034: ['诺艾尔', '诺艾尔', '诺艾尔', '诺艾尔', '诺艾尔', '诺艾尔', '诺艾尔', 'Noelle', 'Noelle', 'Noelle', 'Noelle', 'Noelle',
                   'Noelle', 'Noelle', 'Noelle', 'Noelle'],
        10000024: ['北斗', '北斗', '北斗', '北斗', '北斗', '北斗', '北斗', 'Beidou', 'Beidou', 'Beidou', 'Beidou', 'Beidou', 'Beidou',
                   'Beidou', 'Beidou', 'Beidou'],
        10000044: ['辛焱', '辛焱', '辛焱', '辛焱', '辛焱', '辛焱', '辛焱', 'Xinyan', 'Xinyan', 'Xinyan', 'Xinyan', 'Xinyan', 'Xinyan',
                   'Xinyan', 'Xinyan', 'Xinyan'],
        10000062: ['埃洛伊', '埃洛伊', '埃洛伊', '埃洛伊', '埃洛伊', '埃洛伊', '埃洛伊', 'Aloy', 'Aloy', 'Aloy', 'Aloy', 'Aloy', 'Aloy',
                   'Aloy'],
        10000053: ['早柚', '早柚', '早柚', '早柚', '早柚', '早柚', '早柚', 'Sayu', 'Sayu', 'Sayu', 'Sayu', 'Sayu', 'Sayu', 'Sayu',
                   'Sayu', 'Sayu'],
        10000050: ['托马', '托马', '托马', '托马', '托马', '托马', '托马', 'Thoma', 'Thoma', 'Thoma', 'Thoma', 'Thoma', 'Thoma',
                   'Thoma', 'Thoma', 'Thoma'],
        10000064: ['云堇', '云堇', '云堇', '云堇', '云堇', '云堇', '云堇', 'Yun Jin', 'Yun Jin', 'Yun Jin', 'Yun Jin', 'Yun Jin',
                   'Yun Jin', 'Yun Jin', 'Yun Jin', 'Yun Jin'],
        10000065: ['久岐忍', '久岐忍', '久岐忍', '久岐忍', '久岐忍', 'Kuki Shinobu', 'Kuki Shinobu', 'Kuki Shinobu', 'Kuki Shinobu',
                   'Kuki Shinobu', 'Kuki Shinobu', 'Kuki Shinobu'],
        10000059: ['鹿野院平藏', '鹿野院平藏', '鹿野院平藏', '鹿野院平藏', '鹿野院平藏', 'Shikanoin Heizou', 'Shikanoin Heizou',
                   'Shikanoin Heizou', 'Shikanoin Heizou', 'Shikanoin Heizou', 'Shikanoin Heizou', 'Shikanoin Heizou',
                   'Shikanoin Heizou', 'Shikanoin Heizou'],
        10000005: ['旅行者', '旅行者', 'Traveler', 'Traveler', 'Traveler', 'Traveler', 'Traveler', 'Traveler'],
        10000066: ['神里绫人', '神里绫人', 'Kamisato Ayato', 'Kamisato Ayato', 'Kamisato Ayato', 'Kamisato Ayato'],
        10000051: ['优菈', 'Eula', 'Eula', 'Eula', 'Eula'],
        10000026: ['魈', '魈', '魈', 'Xiao', 'Xiao', 'Xiao', 'Xiao', 'Xiao'],
        10000038: ['阿贝多', '阿贝多', '阿贝多', 'Albedo', 'Albedo', 'Albedo', 'Albedo', 'Albedo']}
name_map = {}


def is_ascii(s):
    return all(ord(c) < 128 for c in s)


for val in data.values():
    val = set(val)
    v1, v2 = val
    if is_ascii(v2):
        name_map[v1] = v2
    else:
        name_map[v2] = v1

print(name_map)
